# Generated by Django 3.1.1 on 2020-09-26 13:59

import cloud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='云商名')),
                ('code', models.IntegerField(choices=[(1, '阿里云'), (2, 'AWS国内'), (3, 'AWS海外'), (4, '华为云'), (5, '腾讯云')], default=1, verbose_name='云商代码')),
                ('secret', models.JSONField(default=cloud.models.defaultJson, verbose_name='JSON秘钥')),
                ('status', models.IntegerField(choices=[(1, '启动'), (2, '停止'), (3, '删除')], default=1, verbose_name='状态')),
                ('add_datatime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_datatime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remarks', models.TextField(default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '云商账号',
                'verbose_name_plural': '云商账号',
                'db_table': 'cloud_access',
            },
        ),
        migrations.CreateModel(
            name='CloudFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='云商执行函数名')),
                ('code', models.IntegerField(choices=[(1, '阿里云'), (2, 'AWS国内'), (3, 'AWS海外'), (4, '华为云'), (5, '腾讯云')], default=1, verbose_name='云商代码')),
                ('func', models.CharField(max_length=50, verbose_name='云商执行函数路径')),
                ('product', models.IntegerField(choices=[(1, 'ECS'), (2, 'LB')], default=1, verbose_name='云商代码')),
                ('add_datatime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_datatime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '云商函数',
                'verbose_name_plural': '云商函数',
                'db_table': 'cloud_func',
            },
        ),
        migrations.CreateModel(
            name='CloudRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='地区名')),
                ('region_code', models.CharField(db_index=True, max_length=20, verbose_name='区域代码')),
                ('cloud_code', models.IntegerField(choices=[(1, '阿里云'), (2, 'AWS国内'), (3, 'AWS海外'), (4, '华为云'), (5, '腾讯云')], default=1, verbose_name='云商代码')),
                ('add_datatime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_datatime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '云商区域',
                'verbose_name_plural': '云商区域',
                'db_table': 'cloud_region',
                'unique_together': {('cloud_code', 'region_code')},
            },
        ),
    ]
