# Generated by Django 3.1.1 on 2020-09-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudaccess',
            old_name='add_datatime',
            new_name='add_datetime',
        ),
        migrations.RenameField(
            model_name='cloudaccess',
            old_name='modify_datatime',
            new_name='modify_datetime',
        ),
        migrations.RenameField(
            model_name='cloudfunc',
            old_name='add_datatime',
            new_name='add_datetime',
        ),
        migrations.RenameField(
            model_name='cloudfunc',
            old_name='modify_datatime',
            new_name='modify_datetime',
        ),
        migrations.RenameField(
            model_name='cloudregion',
            old_name='add_datatime',
            new_name='add_datetime',
        ),
        migrations.RenameField(
            model_name='cloudregion',
            old_name='modify_datatime',
            new_name='modify_datetime',
        ),
    ]
