# Generated by Django 3.1.1 on 2020-09-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud', '0002_auto_20200926_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='InstanceId')),
                ('os', models.CharField(default='', max_length=100, verbose_name='OS')),
                ('memory', models.IntegerField(default=0, verbose_name='内存,M')),
                ('cpu', models.IntegerField(default=0, verbose_name='CPU')),
                ('start_detetime', models.DateTimeField(verbose_name='启动时间')),
                ('expire_detetime', models.DateTimeField(verbose_name='过期时间')),
                ('image', models.CharField(default='', max_length=100, verbose_name='镜像IMAGE')),
                ('name', models.CharField(default='', max_length=20, verbose_name='自己定义的名字')),
                ('instance_type', models.CharField(default='', max_length=30, verbose_name='实例类型')),
                ('zone', models.CharField(default='', max_length=30, verbose_name='区域')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudregion', verbose_name='区域')),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
                'db_table': 'cloud_host',
            },
        ),
    ]
