# Generated by Django 3.1.1 on 2020-09-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_host_cloud_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='meta',
            field=models.JSONField(default={}, verbose_name='元数据'),
        ),
    ]
