# Generated by Django 3.1.1 on 2020-09-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_host_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='元数据'),
        ),
    ]
