# Generated by Django 3.1.1 on 2020-09-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_auto_20200928_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='is_upload',
            field=models.BooleanField(default=True, verbose_name='是否更新'),
        ),
    ]
