# Generated by Django 3.1.1 on 2020-09-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud_public', '0001_initial'),
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudip',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='host.host'),
        ),
    ]
